#!/usr/bin/python3

# pylint: disable=invalid-name
# pylint: enable=invalid-name

# Copyright (C) 2024, Benjamin Drung <bdrung@posteo.de>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

"""try to divide a number by zero and crash"""


def divide_by_zero() -> float:
    """Be smarter than math and devide 42 by zero."""
    zero = 0
    return 42 / zero


def main() -> None:
    """Try to divide a number by zero and crash."""
    result = divide_by_zero()
    print(f"42 / 0 = {result}")


if __name__ == "__main__":
    main()
